version: '3'
services:
  db:
    container_name: slykbots-db
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/postgres.db:/var/lib/postgresql/data

  markov:
    container_name: markov
    build:
      dockerfile: bots/markov/Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - db

  muzika:
    container_name: muzika
    build:
      dockerfile: bots/muzika/Dockerfile
      context: .
      args:
        - VERSION
    env_file:
      - .env
