name: Deploy Images to GHCR
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-markov-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './bots/markov'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and Publish Markov Image'
        run: |
          docker build . --tag ghcr.io/slyk26/markov:latest
          docker push ghcr.io/slyk26/markov:latest